services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - SERVICE_FQDN_RESOURCESPACE_80
    volumes:
      - filestore:/var/www/html/filestore
      - config:/var/www/html/include
      - /data/coolify/resourcespace/policy.xml:/etc/ImageMagick-6/policy.xml:ro
    expose:
      - "80"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  filestore:
  config:
